
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace DocumentClassification_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            DocumentClassification.ModelInput sampleData = new DocumentClassification.ModelInput()
            {
                ImageSource = @"D:\Code\MlNetTest\Docs\Invoice\1.png",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = DocumentClassification.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"ImageSource: {@"D:\Code\MlNetTest\Docs\Invoice\1.png"}");


            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
